# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.26)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS realsense2::usb realsense2::rsutils realsense2::realsense-file realsense2::rs_lz4 realsense2::sqlite3_lib realsense2::realdds realsense2::dds realsense2::fastrtps realsense2::eProsima_atomic realsense2::realsense2)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target realsense2::usb
add_library(realsense2::usb INTERFACE IMPORTED)

set_target_properties(realsense2::usb PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/usr/include/libusb-1.0"
  INTERFACE_LINK_LIBRARIES "/usr/lib/x86_64-linux-gnu/libusb-1.0.so"
)

# Create imported target realsense2::rsutils
add_library(realsense2::rsutils STATIC IMPORTED)

set_target_properties(realsense2::rsutils PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "ELPP_NO_DEFAULT_LOG_FILE"
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_LINK_LIBRARIES "dl"
)

# Create imported target realsense2::realsense-file
add_library(realsense2::realsense-file STATIC IMPORTED)

set_target_properties(realsense2::realsense-file PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "AMENT_INDEX_CPP_BUILDING_DLL;CLASS_LOADER_BUILDING_DLL;RCPPUTILS_BUILDING_LIBRARY;_GNU_SOURCE;RCUTILS_BUILDING_DLL;PLUGINLIB__DISABLE_BOOST_FUNCTIONS;ROSBAG2_STORAGE_BUILDING_DLL;ROSBAG2_STORAGE_DEFAULT_PLUGINS_BUILDING_DLL"
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_LINK_LIBRARIES "realsense2::rs_lz4;\$<LINK_ONLY:realsense2::sqlite3_lib>"
)

# Create imported target realsense2::rs_lz4
add_library(realsense2::rs_lz4 STATIC IMPORTED)

# Create imported target realsense2::sqlite3_lib
add_library(realsense2::sqlite3_lib STATIC IMPORTED)

set_target_properties(realsense2::sqlite3_lib PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:Threads::Threads>;\$<LINK_ONLY:dl>"
)

# Create imported target realsense2::realdds
add_library(realsense2::realdds STATIC IMPORTED)

set_target_properties(realsense2::realdds PROPERTIES
  INTERFACE_LINK_LIBRARIES "realsense2::rsutils;realsense2::dds"
)

# Create imported target realsense2::dds
add_library(realsense2::dds INTERFACE IMPORTED)

set_target_properties(realsense2::dds PROPERTIES
  INTERFACE_LINK_LIBRARIES "fastcdr;realsense2::fastrtps"
)

# Create imported target realsense2::fastrtps
add_library(realsense2::fastrtps STATIC IMPORTED)

set_target_properties(realsense2::fastrtps PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "fastcdr;foonathan_memory;-lpthread;dl;\$<\$<BOOL:0>:OpenSSL::SSL\$<SEMICOLON>OpenSSL::Crypto\$<\$<BOOL:>:\$<SEMICOLON>crypt32.lib>>;\$<\$<BOOL:>:iphlpapi\$<SEMICOLON>Shlwapi>;-lpthread;rt;\$<LINK_ONLY:realsense2::eProsima_atomic>"
)

# Create imported target realsense2::eProsima_atomic
add_library(realsense2::eProsima_atomic INTERFACE IMPORTED)

# Create imported target realsense2::realsense2
add_library(realsense2::realsense2 SHARED IMPORTED)

set_target_properties(realsense2::realsense2 PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_11"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "realsense2::rsutils"
)

if(CMAKE_VERSION VERSION_LESS 3.0.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.0.0 or greater.")
endif()

# Load information for each installed configuration.
file(GLOB _cmake_config_files "${CMAKE_CURRENT_LIST_DIR}/realsense2Targets-*.cmake")
foreach(_cmake_config_file IN LISTS _cmake_config_files)
  include("${_cmake_config_file}")
endforeach()
unset(_cmake_config_file)
unset(_cmake_config_files)

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(_cmake_target IN LISTS _cmake_import_check_targets)
  foreach(_cmake_file IN LISTS "_cmake_import_check_files_for_${_cmake_target}")
    if(NOT EXISTS "${_cmake_file}")
      message(FATAL_ERROR "The imported target \"${_cmake_target}\" references the file
   \"${_cmake_file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_cmake_file)
  unset("_cmake_import_check_files_for_${_cmake_target}")
endforeach()
unset(_cmake_target)
unset(_cmake_import_check_targets)

# Make sure the targets which have been exported in some other
# export set exist.
unset(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)
foreach(_target "fastcdr" "foonathan_memory" )
  if(NOT TARGET "${_target}" )
    set(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets "${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets} ${_target}")
  endif()
endforeach()

if(DEFINED ${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)
  if(CMAKE_FIND_PACKAGE_NAME)
    set( ${CMAKE_FIND_PACKAGE_NAME}_FOUND FALSE)
    set( ${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE "The following imported targets are referenced, but are missing: ${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets}")
  else()
    message(FATAL_ERROR "The following imported targets are referenced, but are missing: ${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets}")
  endif()
endif()
unset(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
